Added Jobs in search option
hotosm/hotosm-website pull request #413
Opened 2019-03-08 21:41 UTC by codefab99

In Response to issue: Add jobs to search #412
Link :https://github.com/hotosm/hotosm-website/issues/412

2019-03-10 11:07 UTC, codefab99 commented
@dakotabenjamin Please review this PR and suggest for changes.

2019-03-11 16:23 UTC, dakotabenjamin commented
Thanks for this PR! I'm having trouble getting the search to load while testing. It looks like the generated JSON is malformed due to a missing comma. I think you need to fix the `unless forloop.last` block in the news part.

2019-03-14 18:27 UTC, codefab99 commented
@dakotabenjamin Thanks for your response. I performed the suggested changes. Please review and suggest changes.

2019-03-14 18:59 UTC, dakotabenjamin requested changes
See comments for requested changes.

2019-03-14 18:59 UTC, dakotabenjamin commented on search.json
>  } {% unless forloop.last %},{% endunless %}
This line is the one I'm referring to- this will always be a comma, so the `unless` condition applies to the next block.

2019-03-14 18:59 UTC, dakotabenjamin commented on search.json
> +"subtitle":"{{ jobs['Place of Work'] | join: ', ' }}",
This text block will need to be stripped and escaped or there's a chance the resulting json will be invalid.

2019-03-14 18:59 UTC, dakotabenjamin commented on search.json
> +{
You should also create a condition that let's users know if the job is past the deadline, perhaps by prepending some text to the title if it is closed.

2019-03-14 20:29 UTC, closed without merging