Clear button added
hotosm/hotosm-website pull request #449
Opened 2019-03-17 07:10 UTC by richa208

Fixes #437 

![hot](https://user-images.githubusercontent.com/25206394/54486667-8c31dc80-48b1-11e9-9ac2-5e50f6166dd6.gif)

@smit1678 @ramyaragupathy Kindly review this.

2019-03-18 09:49 UTC, ramyaragupathy commented on _sass/base.scss
> -  background-image: url(../images/icon-search.svg);
Try retaining this block and play around a little with opacity or jquery attribute fetch

2019-03-18 09:49 UTC, ramyaragupathy commented on js/main.js
> +    $('#search-input').css({'background-image' : 'url(../images/icon-search.svg)', 'background-repeat' : 'no-repeat', 'background-size':'18px 18 px', 'background-position': 'right 14px center'});
Please avoid inline styles as it leads to code redundancy. Try playing around with opacity or jquery attribute fetch

2019-03-18 09:49 UTC, ramyaragupathy commented on js/main.js
> +  $('#search-input').css({'background-image' : '', 'background-repeat' : '', 'background-size':'', 'background-position': ''});
Please avoid inline styles as it leads to code redundancy. Try playing around with opacity or jquery attribute fetch

2019-03-18 13:42 UTC, richa208 commented
@ramyaragupathy Suggested changes have been done.
Kindly review it and suggest if it needs improvement.

2019-03-19 08:32 UTC, ramyaragupathy commented
ok - this works well in Chrome, but the cancel button doesn't show up in Firefox

2019-03-19 10:04 UTC, ramyaragupathy requested changes
From the [documentation for webkit cancel button](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button) - this is not a standard feature and hence will not work on every browser. There is no point digging into this further @richa208 in this direction. Suggest you think of other design solutions here @richa208

2019-03-19 10:10 UTC, richa208 commented
Yes @ramyaragupathy I also found out that it works on selected browsers only. 
Will update the PR with appropriate solution soon.

2019-03-19 13:01 UTC, richa208 commented
@ramyaragupathy I made some changes in the UI by adding a clear button as I was not able to attach a click event on the background image.

![hot4](https://user-images.githubusercontent.com/25206394/54607740-1b3b2200-4a75-11e9-9fbf-5f82ad81ce85.gif)

Kindly tell if it needs more improvement.

2019-03-20 04:09 UTC, ramyaragupathy commented
Not completely convinced about having a button outside as I don't find it adding to the user experience. I suggest let's close it here @richa208 and may be you could post other improvised search design options in your ticket. Let's not rush for any quick fix as it not a pressing problem or a bug.

2019-03-20 05:39 UTC, richa208 commented
Sure @ramyaragupathy as you find it better for the website. 
I will post other design options in the ticket if they are appropriate.

2019-03-20 05:45 UTC, ramyaragupathy commented
Thanks @richa208 - closing this here now

2019-03-20 05:45 UTC, closed without merging