Remove HTML tags from search-text
hotosm/hotosm-website pull request #486
Opened 2019-03-21 09:58 UTC by codefab99

Fixes #482 . @ramyaragupathy Now the search text displays plain text and no HTML tags are shown.
![Screenshot from 2019-03-21 15-27-04](https://user-images.githubusercontent.com/43119923/54744823-f74f1c00-4bed-11e9-8531-3dad82a05b7d.jpg)

Please review this PR and provide suggestions

2019-04-14 10:45 UTC, ramyaragupathy requested changes
Great that you spotted this issue @codefab99. All these links should still be retained within the project files and I am able to click these links individually as well. There seems to be no issue with the way links work.

Suggest you improvise on the search behaviour for projects rather than removing links from summary text.

2019-04-15 18:50 UTC, codefab99 commented
@ramyaragupathy the whole search result is integrated inside `<a>` tags so the individual links are not clickable when search overlay is open. Once the user clicks the result and gets redirected to the page then the links are clickable. So I did not change the links in the main article. The `[Summary Text]` has no links when on the Search-Overlay.

2019-04-16 05:33 UTC, ramyaragupathy commented
You're right @codefab99 - this doesn't seem to affect the links in the summary text 👍

2019-04-16 05:34 UTC, ramyaragupathy approved these changes

2019-04-16 05:34 UTC, merged