Fix hover effect in volunteer page #504
hotosm/hotosm-website pull request #506
Opened 2019-03-25 01:07 UTC by Muskan284

fixes #504 
@ramyaragupathy  kindly review this pr.

2019-03-25 17:55 UTC, harshvardhana25 commented on volunteer.markdown
> +<a href="https://tasks.hotosm.org/learn" class="btn btn-hover btn-primary btn-lg btn-chevron">Learn how to map</a>
If we change this with :- <a href="https://tasks.hotosm.org/learn" class="btn btn-hover btn-primary btn-lg btn-chevron"><color : white>Learn how to map</color></a>

2019-03-25 18:04 UTC, jayshree1602 commented on _sass/base.scss
> +    }
At line no 436

 &.btn-primary {
    color: $white;
    background-color: $red;
    &:hover {
color: white;
      background-color: shade($red, 15%)
    }

2019-03-28 19:49 UTC, ramyaragupathy requested changes
Per code [here](https://github.com/hotosm/hotosm-website/blob/gh-pages/_sass/base.scss#L184-L189), hrefs as a child under `<p>` defaults to red color on hover. So instead of creating a new class under `Buttons` section, you could add additional condition to the referred block and control the behaviour.

2019-03-29 01:45 UTC, Muskan284 commented
@ramyaragupathy I have removed the extra class i created earlier. Kindly review this .

2019-03-29 17:43 UTC, Muskan284 commented
@ramyaragupathy Kindly review this updated pr.

2019-03-31 04:55 UTC, Muskan284 commented
@ramyaragupathy Kindly review this updated pr.

2019-04-14 09:49 UTC, ramyaragupathy approved these changes

2019-04-14 09:50 UTC, merged