Share buttons added in news section
hotosm/hotosm-website pull request #530
Opened 2019-04-08 05:00 UTC by richa208

Fixes #525 

![hot11](https://user-images.githubusercontent.com/25206394/55699611-2dabda00-59e9-11e9-94f9-1a6dcf39220e.gif)

@ramyaragupathy @smit1678 Kindly review this.

2019-04-08 14:35 UTC, codefab99 commented
Hey @richa208 considering thw uniformity of the website I suggest the buttons of share to be of the same hex colour as being used throughout the site.
Also share options should be in the left section in the div which is fixed, for better UX.

2019-04-08 14:37 UTC, bismitaguha requested changes
Share options should be fixed on scroll for better user-experience. Also their colours should be uniform with the website colours.

2019-04-08 18:18 UTC, richa208 commented
Hi @codefab99 
I included those icons for a change. IMO UX can vary according to every person as they feel appropriate.
So I think @ramyaragupathy @dakotabenjamin @smit1678 can best tell what design would be appropriate.

2019-04-08 18:35 UTC, codefab99 commented
Sharing with ease should be there. I was **suggesting** fixed div as an option. @richa208

2019-04-08 20:04 UTC, bismitaguha requested changes

2019-04-08 20:04 UTC, bismitaguha commented on _layouts/news-item.html
> +      <img id="share-buttons" src="/images/Twitter.png" alt="Twitter" ></img>
Using fa icons is preferable rather than png.

2019-04-08 20:04 UTC, codefab99 commented on _sass/base.scss
> +  color:#fff !important;
Using !important in CSS is not a good practice.

2019-04-13 04:12 UTC, ramyaragupathy reviewed
Thanks for working on this @richa208! Adding my thoughts here:
- We already have most of the social media icons in our [image resources](https://github.com/hotosm/hotosm-website/tree/gh-pages/images). Please try using the same for the share feature
-  A few ideas on share feature placement within the page:
Should we have feature as a sticky menu on the left sidebar, similar to `Associated Projects` in the gif attached?
![sticky](https://user-images.githubusercontent.com/12103383/56074060-b223a180-5dc9-11e9-92cd-a43634c90809.gif)


Your current icon placement is at the end of the page right above the footer and on a mobile view this appears  below the side bar content
![image](https://user-images.githubusercontent.com/12103383/56074195-ca94bb80-5dcb-11e9-8d43-f665510a6539.png).
So just adding these icons to the side bar as a sticky menu wouldn't make a difference for the mobile view, but it would add to the user engagement on a desktop.

- However placement of icons is also dependant on how we want the share to operate on our page. Do we go with a modal/ tab /expandable div just below the icons?
In our case share feature transition is temporary and the focus of the user has to return to our news page/website after transmitting the information. So a new tab option is ruled out. We're left with either a modal or a div. A modal works good in desktop. However certain mobile browsers might not support modal well. I see the modal opening as a new tab while simulating the experience in a desktop browser. 
Based on this, I am leaning towards offering the share content feature as an expandable div within the same page. In that case your current placement of icons should work good so that we have enough room to accommodate a div with the share content. 

@richa208 - I would like to hear your thoughts on how we should offer the share feature considering end users on different platforms(mobile & desktop). Our key goal is increasing user engagement and retain user stay within website.

2019-05-22 20:21 UTC, ramyaragupathy commented
Stale - let's revisit based on user interviews

2019-05-22 20:21 UTC, closed without merging