Update: program page
hotosm/hotosm-website pull request #851
Opened 2024-03-14 10:58 UTC by Claurt07

Fixes #[Add issue number here]

Changes: 
- Fixed formatting issues
- added countries to carrousel 

Screenshots of the change: 
<img width="1052" alt="image" src="https://github.com/hotosm/hotosm-website/assets/77023236/d46f2bbf-0d46-4785-892e-731c1c53782a">

2024-03-14 11:00 UTC, Claurt07 commented
@kshitijrajsharma @dakotabenjamin Thanks as always! some fixes to the program page requested by leadership.

2024-03-14 15:42 UTC, dakotabenjamin requested changes
Some minor typos and a big question about the new javascript code. 

Is this code from an existing third party module of some sort? If so we should rather pull it in from a link rather than commit it to code- this will avoid any copyright issues and make it easier to maintain. At present the code in the tailwind-js-carrousel.js file is largely unreadable so I can't review it. It looks like code that has already been minimized.

2024-03-14 15:42 UTC, dakotabenjamin commented on js/tailwindcss-js-carrousel.js
What is the source of this code? It's difficult to understand. Did you write this or is it from an existing third party source?

2024-03-14 15:42 UTC, dakotabenjamin commented on _programs/mapping-for-climate-ready-cities.markdown
> +  Objective3: " ITEGRATION"
Typo

2024-03-14 15:42 UTC, dakotabenjamin commented on _layouts/program-item.html
> +                                            <span class="tooltiptext">Connecting local organizations with local stakeholders and govermnets</span>
Typo

2024-03-14 22:38 UTC, Claurt07 commented on js/tailwindcss-js-carrousel.js
Hi Dakota - I took it from this site https://github.com/tailwindlabs/tailwindcss -- MIT license.
I named the file after the cdn link (https://cdn.tailwindcss.com/) so it is clear where it comes.
I did not load it as CDN directly like the other js files because I needed to make some minor changes to the code.

2024-03-15 22:59 UTC, Claurt07 commented
The Typos, I already took note and will correct them on Siteleaf, there has to be a last review by comms on the text on content so its not final. thank you dk :)

2024-03-20 02:05 UTC, kshitijrajsharma commented on _layouts/program-item.html
> +                <html>
This html section looks repetitive, Can you check ?

2024-03-20 02:09 UTC, kshitijrajsharma commented
You are using tailwind css carrousel. Do mention this in PR and the reason behind for you to import the lib itself . Importing lib is okay , I just want to make sure whoever comes to this PR after will know why you made this decision instead of cdn. 

One more small comment on css : I noticed your media css on base css, While testing you can have multiple views like phone, tablet and web . Based on which you can make sure carrousel doesn't get carried away when screen size changes . I think a lot of people will use cellphone browsing hot website

2024-03-20 03:48 UTC, Claurt07 commented on _programs/mapping-for-climate-ready-cities.markdown
> +  Objective3: " ITEGRATION"
corrected

2024-03-20 03:48 UTC, Claurt07 commented on _layouts/program-item.html
> +                                            <span class="tooltiptext">Connecting local organizations with local stakeholders and govermnets</span>
corrected

2024-03-20 03:49 UTC, Claurt07 commented on _layouts/program-item.html
> +                <html>
Deleted the repeating section

2024-03-21 08:57 UTC, kshitijrajsharma approved these changes

2024-03-21 08:59 UTC, merged